/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WelcomeIndexRouteImport } from './routes/welcome/index'
import { Route as UpdatePasswordIndexRouteImport } from './routes/update-password/index'
import { Route as SpotsIndexRouteImport } from './routes/spots/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as FeedIndexRouteImport } from './routes/feed/index'
import { Route as ContestsIndexRouteImport } from './routes/contests/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SpotsNewRouteImport } from './routes/spots/new'
import { Route as SpotsSpotIdRouteImport } from './routes/spots/$spotId'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as ContestsContestIdRouteImport } from './routes/contests/$contestId'
import { Route as ChatConversationIdRouteImport } from './routes/chat/$conversationId'
import { Route as AdminContestsRouteImport } from './routes/admin/contests'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeIndexRoute = WelcomeIndexRouteImport.update({
  id: '/welcome/',
  path: '/welcome/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePasswordIndexRoute = UpdatePasswordIndexRouteImport.update({
  id: '/update-password/',
  path: '/update-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotsIndexRoute = SpotsIndexRouteImport.update({
  id: '/spots/',
  path: '/spots/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/spots/index.lazy').then((d) => d.Route))
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profile/index.lazy').then((d) => d.Route))
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIndexRoute = FeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/feed/index.lazy').then((d) => d.Route))
const ContestsIndexRoute = ContestsIndexRouteImport.update({
  id: '/contests/',
  path: '/contests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))
const SpotsNewRoute = SpotsNewRouteImport.update({
  id: '/spots/new',
  path: '/spots/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotsSpotIdRoute = SpotsSpotIdRouteImport.update({
  id: '/spots/$spotId',
  path: '/spots/$spotId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsContestIdRoute = ContestsContestIdRouteImport.update({
  id: '/contests/$contestId',
  path: '/contests/$contestId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConversationIdRoute = ChatConversationIdRouteImport.update({
  id: '/chat/$conversationId',
  path: '/chat/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContestsRoute = AdminContestsRouteImport.update({
  id: '/admin/contests',
  path: '/admin/contests',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/admin/contests': typeof AdminContestsRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/contests/$contestId': typeof ContestsContestIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/spots/$spotId': typeof SpotsSpotIdRoute
  '/spots/new': typeof SpotsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/contests/': typeof ContestsIndexRoute
  '/feed/': typeof FeedIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/spots/': typeof SpotsIndexRoute
  '/update-password/': typeof UpdatePasswordIndexRoute
  '/welcome/': typeof WelcomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/admin/contests': typeof AdminContestsRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/contests/$contestId': typeof ContestsContestIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/spots/$spotId': typeof SpotsSpotIdRoute
  '/spots/new': typeof SpotsNewRoute
  '/admin': typeof AdminIndexRoute
  '/chat': typeof ChatIndexRoute
  '/contests': typeof ContestsIndexRoute
  '/feed': typeof FeedIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/login': typeof LoginIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/signup': typeof SignupIndexRoute
  '/spots': typeof SpotsIndexRoute
  '/update-password': typeof UpdatePasswordIndexRoute
  '/welcome': typeof WelcomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/admin/contests': typeof AdminContestsRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/contests/$contestId': typeof ContestsContestIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/spots/$spotId': typeof SpotsSpotIdRoute
  '/spots/new': typeof SpotsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/contests/': typeof ContestsIndexRoute
  '/feed/': typeof FeedIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/spots/': typeof SpotsIndexRoute
  '/update-password/': typeof UpdatePasswordIndexRoute
  '/welcome/': typeof WelcomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/terms'
    | '/admin/contests'
    | '/chat/$conversationId'
    | '/contests/$contestId'
    | '/profile/$username'
    | '/spots/$spotId'
    | '/spots/new'
    | '/admin/'
    | '/chat/'
    | '/contests/'
    | '/feed/'
    | '/forgot-password/'
    | '/login/'
    | '/notifications/'
    | '/profile/'
    | '/signup/'
    | '/spots/'
    | '/update-password/'
    | '/welcome/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/terms'
    | '/admin/contests'
    | '/chat/$conversationId'
    | '/contests/$contestId'
    | '/profile/$username'
    | '/spots/$spotId'
    | '/spots/new'
    | '/admin'
    | '/chat'
    | '/contests'
    | '/feed'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/signup'
    | '/spots'
    | '/update-password'
    | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/terms'
    | '/admin/contests'
    | '/chat/$conversationId'
    | '/contests/$contestId'
    | '/profile/$username'
    | '/spots/$spotId'
    | '/spots/new'
    | '/admin/'
    | '/chat/'
    | '/contests/'
    | '/feed/'
    | '/forgot-password/'
    | '/login/'
    | '/notifications/'
    | '/profile/'
    | '/signup/'
    | '/spots/'
    | '/update-password/'
    | '/welcome/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TermsRoute: typeof TermsRoute
  AdminContestsRoute: typeof AdminContestsRoute
  ChatConversationIdRoute: typeof ChatConversationIdRoute
  ContestsContestIdRoute: typeof ContestsContestIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  SpotsSpotIdRoute: typeof SpotsSpotIdRoute
  SpotsNewRoute: typeof SpotsNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ContestsIndexRoute: typeof ContestsIndexRoute
  FeedIndexRoute: typeof FeedIndexRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  SpotsIndexRoute: typeof SpotsIndexRoute
  UpdatePasswordIndexRoute: typeof UpdatePasswordIndexRoute
  WelcomeIndexRoute: typeof WelcomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/': {
      id: '/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof WelcomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password/': {
      id: '/update-password/'
      path: '/update-password'
      fullPath: '/update-password/'
      preLoaderRoute: typeof UpdatePasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spots/': {
      id: '/spots/'
      path: '/spots'
      fullPath: '/spots/'
      preLoaderRoute: typeof SpotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/': {
      id: '/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof FeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests/': {
      id: '/contests/'
      path: '/contests'
      fullPath: '/contests/'
      preLoaderRoute: typeof ContestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spots/new': {
      id: '/spots/new'
      path: '/spots/new'
      fullPath: '/spots/new'
      preLoaderRoute: typeof SpotsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spots/$spotId': {
      id: '/spots/$spotId'
      path: '/spots/$spotId'
      fullPath: '/spots/$spotId'
      preLoaderRoute: typeof SpotsSpotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests/$contestId': {
      id: '/contests/$contestId'
      path: '/contests/$contestId'
      fullPath: '/contests/$contestId'
      preLoaderRoute: typeof ContestsContestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$conversationId': {
      id: '/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof ChatConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contests': {
      id: '/admin/contests'
      path: '/admin/contests'
      fullPath: '/admin/contests'
      preLoaderRoute: typeof AdminContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TermsRoute: TermsRoute,
  AdminContestsRoute: AdminContestsRoute,
  ChatConversationIdRoute: ChatConversationIdRoute,
  ContestsContestIdRoute: ContestsContestIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  SpotsSpotIdRoute: SpotsSpotIdRoute,
  SpotsNewRoute: SpotsNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  ContestsIndexRoute: ContestsIndexRoute,
  FeedIndexRoute: FeedIndexRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  SpotsIndexRoute: SpotsIndexRoute,
  UpdatePasswordIndexRoute: UpdatePasswordIndexRoute,
  WelcomeIndexRoute: WelcomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
