/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as SpotsNewRouteImport } from './routes/spots/new'
import { Route as SpotsSpotIdRouteImport } from './routes/spots/$spotId'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotsNewRoute = SpotsNewRouteImport.update({
  id: '/spots/new',
  path: '/spots/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotsSpotIdRoute = SpotsSpotIdRouteImport.update({
  id: '/spots/$spotId',
  path: '/spots/$spotId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/spots/$spotId': typeof SpotsSpotIdRoute
  '/spots/new': typeof SpotsNewRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/signup': typeof SignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/spots/$spotId': typeof SpotsSpotIdRoute
  '/spots/new': typeof SpotsNewRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/signup': typeof SignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/spots/$spotId': typeof SpotsSpotIdRoute
  '/spots/new': typeof SpotsNewRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/signup/': typeof SignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile/$username'
    | '/spots/$spotId'
    | '/spots/new'
    | '/login'
    | '/profile'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile/$username'
    | '/spots/$spotId'
    | '/spots/new'
    | '/login'
    | '/profile'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/profile/$username'
    | '/spots/$spotId'
    | '/spots/new'
    | '/login/'
    | '/profile/'
    | '/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  SpotsSpotIdRoute: typeof SpotsSpotIdRoute
  SpotsNewRoute: typeof SpotsNewRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spots/new': {
      id: '/spots/new'
      path: '/spots/new'
      fullPath: '/spots/new'
      preLoaderRoute: typeof SpotsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spots/$spotId': {
      id: '/spots/$spotId'
      path: '/spots/$spotId'
      fullPath: '/spots/$spotId'
      preLoaderRoute: typeof SpotsSpotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  SpotsSpotIdRoute: SpotsSpotIdRoute,
  SpotsNewRoute: SpotsNewRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
